# Generated by Django 4.2.3 on 2023-07-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='preview',
            new_name='image',
        ),
    ]
